#ifndef WORLD_CONFIG_H
#define WORLD_CONFIG_H

#define WORLD_ROOM_MIN_X -15.0f
#define WORLD_ROOM_MAX_X 15.0f
#define WORLD_ROOM_MIN_Z -15.0f
#define WORLD_ROOM_MAX_Z 15.0f

#define WORLD_COLUMN_MIN_HEIGHT 1.0f
#define WORLD_COLUMN_MAX_HEIGHT 12.0f
#define WORLD_COLUMN_RADIUS 1.0f

#define WORLD_PLAYER_COLLISION_RADIUS 0.5f
#define WORLD_WALL_THICKNESS 1.0f
#define WORLD_ROOF_UNDERSIDE_Y 18.0f
#define WORLD_ROOF_THICKNESS 1.0f

#endif
