#ifndef WORLD_CONFIG_H
#define WORLD_CONFIG_H

#define WORLD_ROOM_MIN_X -15.0f
#define WORLD_ROOM_MAX_X 15.0f
#define WORLD_ROOM_MIN_Z -15.0f
#define WORLD_ROOM_MAX_Z 15.0f

#define WORLD_BLOCK_MIN_HEIGHT 0.9f
#define WORLD_BLOCK_MAX_HEIGHT 12.0f
#define WORLD_BLOCK_HALF_X 1.0f
#define WORLD_BLOCK_LEVEL_HEIGHT 0.9f
#define WORLD_BLOCK_HEIGHT_Y (WORLD_BLOCK_LEVEL_HEIGHT * 2.0f)
#define WORLD_BLOCK_DEPTH_Z (WORLD_BLOCK_LEVEL_HEIGHT * 2.0f)
#define WORLD_BLOCK_HALF_Z (WORLD_BLOCK_DEPTH_Z * 0.5f)
#define WORLD_BLOCK_MIN_LEVEL 1
#define WORLD_BLOCK_MAX_LEVEL 13
#define WORLD_BLOCK_DEFAULT_LEVEL_ONE_COUNT 4u
#define WORLD_BLOCK_DEFAULT_MIN_BLOCKS_PER_LEVEL 2u
#define WORLD_BLOCK_DEFAULT_MAX_BLOCKS_PER_LEVEL 4u
#define WORLD_BLOCK_DEFAULT_MIN_TOP_LEVEL_PATHS 2u
#define WORLD_BLOCK_DEFAULT_MIN_JUMPABLE_DISTANCE 2.25f
#define WORLD_BLOCK_DEFAULT_MAX_JUMPABLE_DISTANCE 4.0f
#define WORLD_BLOCK_DEFAULT_PREFERRED_GAP_MIN 2.35f
#define WORLD_BLOCK_DEFAULT_PREFERRED_GAP_MAX 3.35f
#define WORLD_BLOCK_DEFAULT_HARD_GAP_CHANCE 0.30f
#define WORLD_BLOCK_DEFAULT_COVERAGE_BIAS 0.70f
#define WORLD_BLOCK_DEFAULT_OVERHEAD_CLEARANCE_LEVELS 2
#define WORLD_BLOCK_DEFAULT_OVERHEAD_CLEARANCE_MARGIN WORLD_PLAYER_COLLISION_RADIUS
#define WORLD_BLOCK_GENERATION_AHEAD_LEVELS 8
#define WORLD_BLOCK_ACTIVE_BEHIND_LEVELS 4
#define WORLD_BLOCK_STREAM_LEVEL_ONE_COUNT 8u
#define WORLD_BLOCK_STREAM_MIN_BLOCKS_PER_LEVEL 6u
#define WORLD_BLOCK_STREAM_MAX_BLOCKS_PER_LEVEL 10u
#define WORLD_BLOCK_STREAM_MIN_TOP_LEVEL_PATHS 3u
#define WORLD_BLOCK_STREAM_COVERAGE_BIAS 0.90f

#define WORLD_PLAYER_COLLISION_RADIUS 0.5f
#define WORLD_WALL_THICKNESS 1.0f
#define WORLD_ROOF_UNDERSIDE_Y 18.0f
#define WORLD_ROOF_THICKNESS 1.0f

#endif
