#ifndef WORLD_CONFIG_H
#define WORLD_CONFIG_H

#define WORLD_ROOM_MIN_X -15.0f
#define WORLD_ROOM_MAX_X 15.0f
#define WORLD_ROOM_MIN_Z -15.0f
#define WORLD_ROOM_MAX_Z 15.0f

#define WORLD_COLUMN_MIN_HEIGHT 0.9f
#define WORLD_COLUMN_MAX_HEIGHT 12.0f
#define WORLD_COLUMN_RADIUS 1.0f
#define WORLD_PILLAR_LEVEL_HEIGHT 0.9f
#define WORLD_PILLAR_MIN_LEVEL 1
#define WORLD_PILLAR_MAX_LEVEL 13
#define WORLD_PILLAR_DEFAULT_CHAIN_LENGTH 13u
#define WORLD_PILLAR_DEFAULT_MIN_JUMPABLE_DISTANCE 2.25f
#define WORLD_PILLAR_DEFAULT_MAX_JUMPABLE_DISTANCE 4.0f
#define WORLD_PILLAR_DEFAULT_NEARBY_CHANCE 0.70f
#define WORLD_PILLAR_DEFAULT_UPWARD_CHANCE 0.45f
#define WORLD_PILLAR_DEFAULT_MAX_EXTRA_LEVEL_DELTA 1

#define WORLD_PLAYER_COLLISION_RADIUS 0.5f
#define WORLD_WALL_THICKNESS 1.0f
#define WORLD_ROOF_UNDERSIDE_Y 18.0f
#define WORLD_ROOF_THICKNESS 1.0f

#endif
